# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diemdanh.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QImage, QPixmap
import cv2, imutils
import time
import numpy as np

faceCascade = cv2.CascadeClassifier(cv2.data.haarcascades +'haarcascade_frontalface_default.xml')
import numpy as np
import cv2
import pyshine as ps


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1271, 896)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setTabletTracking(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_dd = QtWidgets.QWidget()
        self.tab_dd.setObjectName("tab_dd")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_dd)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_cam = QtWidgets.QLabel(self.tab_dd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cam.sizePolicy().hasHeightForWidth())
        self.label_cam.setSizePolicy(sizePolicy)
        self.label_cam.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.label_cam.setText("")
        self.label_cam.setObjectName("label_cam")
        self.horizontalLayout_3.addWidget(self.label_cam)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_startcam = QtWidgets.QPushButton(self.tab_dd)
        self.btn_startcam.setObjectName("btn_startcam")
        self.verticalLayout.addWidget(self.btn_startcam)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_2.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.formLayout_2.setHorizontalSpacing(0)
        self.formLayout_2.setVerticalSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_13 = QtWidgets.QLabel(self.tab_dd)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.cbb_monhoc = QtWidgets.QComboBox(self.tab_dd)
        self.cbb_monhoc.setObjectName("cbb_monhoc")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbb_monhoc)
        self.label_14 = QtWidgets.QLabel(self.tab_dd)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.dateTimeEdi = QtWidgets.QDateTimeEdit(self.tab_dd)
        self.dateTimeEdi.setObjectName("dateTimeEdi")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdi)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.tableView_dssv = QtWidgets.QTableView(self.tab_dd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_dssv.sizePolicy().hasHeightForWidth())
        self.tableView_dssv.setSizePolicy(sizePolicy)
        self.tableView_dssv.setObjectName("tableView_dssv")
        self.verticalLayout.addWidget(self.tableView_dssv)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_dd, "")
        self.tab_Themsv = QtWidgets.QWidget()
        self.tab_Themsv.setObjectName("tab_Themsv")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_Themsv)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab_Themsv)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_Themsv)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_3)
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup.addButton(self.radioButton_4)
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.radioButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.pushButton_5)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.gridLayout_3.addWidget(self.groupBox, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        self.label_7.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_7.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(170, 170, 0);")
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab_Themsv, "")
        self.tab_lop = QtWidgets.QWidget()
        self.tab_lop.setObjectName("tab_lop")
        self.tabWidget.addTab(self.tab_lop, "")
        self.tab_mhoc = QtWidgets.QWidget()
        self.tab_mhoc.setObjectName("tab_mhoc")
        self.tabWidget.addTab(self.tab_mhoc, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.btn_startcam.clicked.connect(self.loadcam)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.filename = 'Snapshot ' + str(
            time.strftime("%Y-%b-%d at %H.%M.%S %p")) + '.png'  # Will hold the image address location
        self.tmp = None  # Will hold the temporary image for display
        self.brightness_value_now = 0  # Updated brightness value
        self.blur_value_now = 0  # Updated blur value
        self.fps = 0
        self.started = False

    def loadcam(self):

        if self.started:
            self.started = False
            self.btn_startcam.setText('Bắt đầu điểm danh')
        else:
            self.started = True
            self.btn_startcam.setText('Kết thúc điểm danh')


        vid = cv2.VideoCapture(0)

        print(vid.isOpened())
        while (vid.isOpened()):
            img, frame = vid.read()
            frame = imutils.resize(frame, height=600, width=800)
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            faces = faceCascade.detectMultiScale(
                gray,
                scaleFactor=1.12,
                minNeighbors=5,
                minSize=(30, 30)
                #flags=cv2.CV_HAAR_SCALE_IMAGE
            )
            for (x, y, w, h) in faces:
                cv2.rectangle(frame, (x, y), (x + w, y + h), (10, 228, 220), 2)
            print('this')
            self.displayImage(frame,1)

            key = cv2.waitKey(1) & 0xFF
            if self.started == False:
                break
                print('Loop break')

    def displayImage(self, img,window=1):
        qformat = QImage.Format_Indexed8

        if len(img.shape) == 3:
            if (img.shape[2]) == 4:
                qformat = QImage.Format_RGBA888
            else:
                qformat = QImage.Format_RGB888
        img = QImage(img, img.shape[1], img.shape[0],qformat)
        imf = img.rgbSwapped()
        self.label_cam.setPixmap(QPixmap.fromImage(img))
        self.label_cam.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Phần Mền Điểm Danh"))
        self.btn_startcam.setText(_translate("MainWindow", "khỏi động camera"))
        self.label_13.setText(_translate("MainWindow", "Môn học :"))
        self.label_14.setText(_translate("MainWindow", "Ngày điểm danh :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_dd), _translate("MainWindow", "Điểm Danh"))
        self.label.setText(_translate("MainWindow", "                                                  khu vực camera"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Lấy Khuôn Mặt"))
        self.pushButton_4.setText(_translate("MainWindow", "Bắt Đầu Quét"))
        self.groupBox.setTitle(_translate("MainWindow", "Nhập Thông Tin"))
        self.label_8.setText(_translate("MainWindow", "Họ Tên Sinh Viên :"))
        self.label_9.setText(_translate("MainWindow", "Mã Sinh Viên :"))
        self.label_10.setText(_translate("MainWindow", "Lớp"))
        self.label_11.setText(_translate("MainWindow", "Giới tính:"))
        self.radioButton_3.setText(_translate("MainWindow", "Nam"))
        self.radioButton_4.setText(_translate("MainWindow", "Nữ"))
        self.pushButton_5.setText(_translate("MainWindow", "LƯU"))
        self.label_12.setText(_translate("MainWindow", "Địa Chỉ :"))
        self.label_7.setText(_translate("MainWindow", "     ảnh mặt đã chụp"))
        self.pushButton.setText(_translate("MainWindow", "Khởi Động Camera"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Themsv), _translate("MainWindow", "Thêm sinh viên"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_lop), _translate("MainWindow", "Lớp"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mhoc), _translate("MainWindow", "Môn học"))
