# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(580, 585)
        Form.setStyleSheet("\n"
"*{\n"
"font-family: Century Gothic;\n"
" font-size: 24px;\n"
"}\n"
"QFrame{\n"
"background-color: rgb(51, 51, 51);\n"
"}\n"
"QMainWindow{\n"
"\n"
"}\n"
"QToolButton{\n"
"   border-radius: 50px ;\n"
"   background-color: red;\n"
"}\n"
"QPushButton{\n"
"   border-radius: 60px ;\n"
"   background-color: red;\n"
"}\n"
"QLabel{\n"
" color: white;\n"
"}\n"
"QPushButton{\n"
"   border-radius: 15px ;\n"
"   color: white;\n"
"font-size: 18px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   color: rgb(51, 51, 51);\n"
"\n"
"  border-radius: 15px ;\n"
" background-color:  white;\n"
"font-size: 18px;\n"
"  \n"
"}\n"
"QLineEdit{\n"
"border:none;\n"
" color: gray;\n"
"border-bottom: 1px solid gray;\n"
"font-size: 15px;\n"
"\n"
"\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(120, 90, 341, 401))
        self.frame.setStyleSheet("background-color: rgb(51, 51, 51);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(100, 80, 151, 31))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(50, 180, 241, 31))
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 240, 241, 31))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(240, 40, 101, 101))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../images/icon3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(50, 50))
        self.toolButton.setObjectName("toolButton")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(170, 410, 241, 41))
        self.btn_login.setObjectName("btn_login")
        Form.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Form)
        self.statusbar.setObjectName("statusbar")
        Form.setStatusBar(self.statusbar)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MainWindow"))
        self.label.setText(_translate("Form", "ĐĂNG NHẬP"))
        self.lineEdit.setPlaceholderText(_translate("Form", "tên đăng nhập"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "mật khẩu"))
        self.toolButton.setText(_translate("Form", "..."))
        self.btn_login.setText(_translate("Form", "Đăng Nhập"))

